version: '3.4'
services:
  # database
  db:
    image: "postgres:16.1-alpine"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}


  redis:
    ports:
      - "${REDIS_PORT}:6379"
    image: "redis:7.0.0-alpine"
    restart: always
    environment:
      - REDIS_DATABASES=16
    networks:
      - app.network

networks:
  app.network:
    driver: bridge
